// <auto-generated />
using System;
using BaseApi.Infrastructure.Dados;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BaseApi.Infrastructure.Dados.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260806230852_FixPartidaRodadaMapping")]
    partial class FixPartidaRodadaMapping
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BaseApi.Domain.Entidades.Campeonato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CaminhoImagemCampo")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("CaminhoLogo")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("ChavePix")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DiasDosJogos")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("LimiteEquipes")
                        .HasColumnType("int");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TaxaInscricao")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Campeonatos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            AtualizadoEm = new DateTime(2026, 8, 6, 23, 8, 51, 615, DateTimeKind.Utc).AddTicks(5962),
                            CaminhoImagemCampo = "",
                            CaminhoLogo = "assets/campeonato1.jpg",
                            ChavePix = "",
                            CriadoEm = new DateTime(2026, 8, 6, 23, 8, 51, 615, DateTimeKind.Utc).AddTicks(5959),
                            DataFim = new DateTime(2026, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataInicio = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "",
                            DiasDosJogos = "",
                            LimiteEquipes = 16,
                            Local = "Estádio Municipal",
                            Nome = "Copa Regional Norte 2026",
                            Status = 1,
                            TaxaInscricao = 0m
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            AtualizadoEm = new DateTime(2026, 8, 6, 23, 8, 51, 615, DateTimeKind.Utc).AddTicks(5977),
                            CaminhoImagemCampo = "",
                            CaminhoLogo = "assets/campeonato2.jpg",
                            ChavePix = "",
                            CriadoEm = new DateTime(2026, 8, 6, 23, 8, 51, 615, DateTimeKind.Utc).AddTicks(5977),
                            DataFim = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataInicio = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "",
                            DiasDosJogos = "",
                            LimiteEquipes = 32,
                            Local = "Vários Estádios",
                            Nome = "Liga dos Campeões Amadora",
                            Status = 2,
                            TaxaInscricao = 0m
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            AtualizadoEm = new DateTime(2026, 8, 6, 23, 8, 51, 615, DateTimeKind.Utc).AddTicks(5980),
                            CaminhoImagemCampo = "",
                            CaminhoLogo = "assets/campeonato3.jpg",
                            ChavePix = "",
                            CriadoEm = new DateTime(2026, 8, 6, 23, 8, 51, 615, DateTimeKind.Utc).AddTicks(5980),
                            DataFim = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataInicio = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "",
                            DiasDosJogos = "",
                            LimiteEquipes = 8,
                            Local = "Arena Sul",
                            Nome = "Torneio de Inverno 2025",
                            Status = 3,
                            TaxaInscricao = 0m
                        });
                });

            modelBuilder.Entity("BaseApi.Domain.Entidades.Classificacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CampeonatoId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ClubeId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Derrotas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Empates")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("GolsContra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("GolsPro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("PartidasJogadas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Pontos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Vitorias")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("ClubeId");

                    b.HasIndex("CampeonatoId", "ClubeId")
                        .IsUnique();

                    b.ToTable("Classificacoes", (string)null);
                });

            modelBuilder.Entity("BaseApi.Domain.Entidades.Clube", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AnoFundacao")
                        .HasColumnType("int");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("BreveHistoria")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("CaminhoEscudo")
                        .IsRequired()
                        .HasColumnType("LONGTEXT");

                    b.Property<string>("CidadeEstado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EstadioPrincipal")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("LigaCompeticao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("clubes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            AnoFundacao = 1990,
                            AtualizadoEm = new DateTime(2026, 8, 6, 23, 8, 51, 615, DateTimeKind.Utc).AddTicks(6050),
                            BreveHistoria = "Um clube criado para testes.",
                            CaminhoEscudo = "https://robohash.org/clube1?set=set1",
                            CidadeEstado = "São Paulo / SP",
                            CriadoEm = new DateTime(2026, 8, 6, 23, 8, 51, 615, DateTimeKind.Utc).AddTicks(6050),
                            LigaCompeticao = "Série A",
                            Nome = "Clube Atlético Teste",
                            UsuarioId = new Guid("00000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("BaseApi.Domain.Entidades.InscricaoCampeonato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("AceitouRegulamento")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CaminhoComprovantePagamento")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("CaminhoDocumentoIdentidade")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<Guid>("CampeonatoId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ClubeId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DataResposta")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NomeResponsavel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TelefoneResponsavel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CampeonatoId");

                    b.HasIndex("ClubeId");

                    b.ToTable("InscricoesCampeonatos", (string)null);
                });

            modelBuilder.Entity("BaseApi.Domain.Entidades.Jogador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Altura")
                        .HasColumnType("int");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("BioHistorico")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("CaminhoFoto")
                        .IsRequired()
                        .HasColumnType("LONGTEXT");

                    b.Property<Guid?>("ClubeId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("PePreferencial")
                        .HasColumnType("int");

                    b.Property<double>("Peso")
                        .HasColumnType("double");

                    b.Property<int>("PosicaoPrincipal")
                        .HasColumnType("int");

                    b.Property<int?>("PosicaoSecundaria")
                        .HasColumnType("int");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ClubeId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("jogadores", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Altura = 180,
                            AtualizadoEm = new DateTime(2026, 8, 6, 23, 8, 51, 615, DateTimeKind.Utc).AddTicks(6015),
                            BioHistorico = "Jogador de teste do sistema.",
                            CaminhoFoto = "https://robohash.org/pedro?set=set5",
                            CriadoEm = new DateTime(2026, 8, 6, 23, 8, 51, 615, DateTimeKind.Utc).AddTicks(6015),
                            DataNascimento = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NomeCompleto = "Pedro Oliveira (Teste)",
                            PePreferencial = 3,
                            Peso = 75.0,
                            PosicaoPrincipal = 6,
                            UsuarioId = new Guid("00000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("BaseApi.Domain.Entidades.Partida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ClubeMandanteId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ClubeVisitanteId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("GolsMandante")
                        .HasColumnType("int");

                    b.Property<int?>("GolsVisitante")
                        .HasColumnType("int");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("RodadaId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClubeMandanteId");

                    b.HasIndex("ClubeVisitanteId");

                    b.HasIndex("RodadaId");

                    b.ToTable("Partidas", (string)null);
                });

            modelBuilder.Entity("BaseApi.Domain.Entidades.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("perfis", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Acesso total ao sistema",
                            Nome = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Acesso intermediário ao sistema",
                            Nome = "Gerente"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Acesso básico ao sistema",
                            Nome = "Usuário"
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Perfil de acesso para Jogadores",
                            Nome = "Jogador"
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "Perfil de acesso para Clubes",
                            Nome = "Clube"
                        });
                });

            modelBuilder.Entity("BaseApi.Domain.Entidades.Rodada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CampeonatoId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CampeonatoId");

                    b.ToTable("Rodadas", (string)null);
                });

            modelBuilder.Entity("BaseApi.Domain.Entidades.SolicitacaoClube", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ClubeId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DataResposta")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("JogadorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClubeId");

                    b.HasIndex("JogadorId");

                    b.ToTable("SolicitacoesClubes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            ClubeId = new Guid("11111111-1111-1111-1111-111111111111"),
                            DataSolicitacao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            JogadorId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Mensagem = "Gostaria de participar da seletiva do Clube Atlético Teste.",
                            Status = 1
                        });
                });

            modelBuilder.Entity("BaseApi.Domain.Entidades.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("PerfilId")
                        .HasColumnType("int");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("TokenExpiracao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TokenRedefinicaoSenha")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NomeUsuario")
                        .IsUnique();

                    b.HasIndex("PerfilId");

                    b.ToTable("usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Ativo = true,
                            AtualizadoEm = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@baseapi.com",
                            NomeCompleto = "Administrador do Sistema",
                            NomeUsuario = "admin",
                            PerfilId = 1,
                            SenhaHash = "$2a$11$zTVYyQq9u/tRNQwHa6Xpo.YsiLDzaL6vavcA8Ht/eK0buOUcshiiO"
                        });
                });

            modelBuilder.Entity("BaseApi.Domain.Entidades.Classificacao", b =>
                {
                    b.HasOne("BaseApi.Domain.Entidades.Campeonato", "Campeonato")
                        .WithMany()
                        .HasForeignKey("CampeonatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaseApi.Domain.Entidades.Clube", "Clube")
                        .WithMany()
                        .HasForeignKey("ClubeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campeonato");

                    b.Navigation("Clube");
                });

            modelBuilder.Entity("BaseApi.Domain.Entidades.Clube", b =>
                {
                    b.HasOne("BaseApi.Domain.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BaseApi.Domain.Entidades.InscricaoCampeonato", b =>
                {
                    b.HasOne("BaseApi.Domain.Entidades.Campeonato", "Campeonato")
                        .WithMany()
                        .HasForeignKey("CampeonatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaseApi.Domain.Entidades.Clube", "Clube")
                        .WithMany()
                        .HasForeignKey("ClubeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campeonato");

                    b.Navigation("Clube");
                });

            modelBuilder.Entity("BaseApi.Domain.Entidades.Jogador", b =>
                {
                    b.HasOne("BaseApi.Domain.Entidades.Clube", "Clube")
                        .WithMany()
                        .HasForeignKey("ClubeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BaseApi.Domain.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clube");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BaseApi.Domain.Entidades.Partida", b =>
                {
                    b.HasOne("BaseApi.Domain.Entidades.Clube", "ClubeMandante")
                        .WithMany()
                        .HasForeignKey("ClubeMandanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BaseApi.Domain.Entidades.Clube", "ClubeVisitante")
                        .WithMany()
                        .HasForeignKey("ClubeVisitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BaseApi.Domain.Entidades.Rodada", "Rodada")
                        .WithMany("Partidas")
                        .HasForeignKey("RodadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClubeMandante");

                    b.Navigation("ClubeVisitante");

                    b.Navigation("Rodada");
                });

            modelBuilder.Entity("BaseApi.Domain.Entidades.Rodada", b =>
                {
                    b.HasOne("BaseApi.Domain.Entidades.Campeonato", "Campeonato")
                        .WithMany()
                        .HasForeignKey("CampeonatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campeonato");
                });

            modelBuilder.Entity("BaseApi.Domain.Entidades.SolicitacaoClube", b =>
                {
                    b.HasOne("BaseApi.Domain.Entidades.Clube", "Clube")
                        .WithMany()
                        .HasForeignKey("ClubeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaseApi.Domain.Entidades.Jogador", "Jogador")
                        .WithMany()
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clube");

                    b.Navigation("Jogador");
                });

            modelBuilder.Entity("BaseApi.Domain.Entidades.Usuario", b =>
                {
                    b.HasOne("BaseApi.Domain.Entidades.Perfil", "Perfil")
                        .WithMany("Usuarios")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("BaseApi.Domain.Entidades.Perfil", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("BaseApi.Domain.Entidades.Rodada", b =>
                {
                    b.Navigation("Partidas");
                });
#pragma warning restore 612, 618
        }
    }
}
